---
title: "FinalProject_Brainstorm"
author: "Jack Sylvia"
date: "3/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(rvest)
library(stringr)
library(ggimage)
```

# Individual Liberty League Data

## West

#### SLU
```{r}
url_SLU <- "https://saintsathletics.com/sports/baseball/stats/2022"
tab_SLU <- read_html(url_SLU) %>% html_nodes("table")
SLU_Hitting <- tab_SLU[[1]] %>% html_table(fill = TRUE)
SLU_Pitching <- tab_SLU[[2]] %>% html_table(fill = TRUE)

SLU_Hitting_new <- SLU_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "SLU",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://www.pngfind.com/pngs/m/293-2932598_st-lawrence-university-logo-png-transparent-png.png", size = 1, replace = TRUE)) ## Some images are not very clear. Need to find better png
  

SLU_Pitching_new <- SLU_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "SLU",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://www.pngfind.com/pngs/m/293-2932598_st-lawrence-university-logo-png-transparent-png.png", size = 1, replace = TRUE))

  
```

#### Clarkson
```{r}
url_CU <- "https://clarksonathletics.com/sports/baseball/stats/2022"
tab_CU <- read_html(url_CU) %>% html_nodes("table")
Clarkson_Hitting <- tab_CU[[1]] %>% html_table(fill = TRUE)
Clarkson_Pitching <- tab_CU[[2]] %>% html_table(fill = TRUE)

Clarkson_Hitting_new <- Clarkson_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Clarkson",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://w1.pngwing.com/pngs/125/424/png-transparent-mascot-logo-clarkson-university-clarkson-golden-knights-mens-ice-hockey-clarkson-golden-knights-mens-basketball-clarkson-golden-knights-womens-basketball-clarkson-avenue-athletics.png", size = 1, replace = TRUE))
  

Clarkson_Pitching_new <- Clarkson_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Clarkson",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://w1.pngwing.com/pngs/125/424/png-transparent-mascot-logo-clarkson-university-clarkson-golden-knights-mens-ice-hockey-clarkson-golden-knights-mens-basketball-clarkson-golden-knights-womens-basketball-clarkson-avenue-athletics.png", size = 1, replace = TRUE))
```

#### Rochester
```{r}
url_UofR <- "https://uofrathletics.com/sports/baseball/stats/2022"
tab_UofR <- read_html(url_UofR) %>% html_nodes("table")
Rochester_Hitting <- tab_UofR[[1]] %>% html_table(fill = TRUE)
Rochester_Pitching <- tab_UofR[[2]] %>% html_table(fill = TRUE)

Rochester_Hitting_new <- Rochester_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Rochester",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://uofrathletics.com/images/logos/site/site.png", size = 1, replace = TRUE))

Rochester_Pitching_new <- Rochester_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Rochester",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://uofrathletics.com/images/logos/site/site.png", size = 1, replace = TRUE))
```

#### RIT
```{r}
url_RIT <- "https://ritathletics.com/sports/baseball/stats/2022"
tab_RIT <- read_html(url_RIT) %>% html_nodes("table")
RIT_Hitting <- tab_RIT[[1]] %>% html_table(fill = TRUE)
RIT_Pitching <- tab_RIT[[2]] %>% html_table(fill = TRUE)

RIT_Hitting_new <- RIT_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "RIT",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://www.rit.edu/brandportal/sites/rit.edu.brandportal/files/2020-04/3-color-white%20%281%29.png", size = 1, replace = TRUE))
  

RIT_Pitching_new <- RIT_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "RIT",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://www.rit.edu/brandportal/sites/rit.edu.brandportal/files/2020-04/3-color-white%20%281%29.png", size = 1, replace = TRUE))
```

#### Ithaca
```{r}
url_IC <- "https://athletics.ithaca.edu/sports/baseball/stats/2022"
tab_IC <- read_html(url_IC) %>% html_nodes("table")
Ithaca_Hitting <- tab_IC[[1]] %>% html_table(fill = TRUE)
Ithaca_Pitching <- tab_IC[[2]] %>% html_table(fill = TRUE)

Ithaca_Hitting_new <- Ithaca_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Ithaca",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ithaca_logo_from_NCAA.svg/1200px-Ithaca_logo_from_NCAA.svg.png", size = 1, replace = TRUE))
  

Ithaca_Pitching_new <- Ithaca_Pitching %>%
  head(-2) %>%
  select(-23) %>%
 separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Ithaca",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ithaca_logo_from_NCAA.svg/1200px-Ithaca_logo_from_NCAA.svg.png", size = 1, replace = TRUE))
```

## East

#### Skidmore
```{r}
url_Skid <- "https://skidmoreathletics.com/sports/baseball/stats/2022"
tab_Skid <- read_html(url_Skid) %>% html_nodes("table")
Skidmore_Hitting <- tab_Skid[[1]] %>% html_table(fill = TRUE)
Skidmore_Pitching <- tab_Skid[[2]] %>% html_table(fill = TRUE)

Skidmore_Hitting_new <- Skidmore_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Skidmore",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://storage-thumbnails.bananatag.com/images/vzvwyb/0c54276847e60bdc39fada3aec9cf379.png", size = 1, replace = TRUE))

Skidmore_Pitching_new <- Skidmore_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Skidmore",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://storage-thumbnails.bananatag.com/images/vzvwyb/0c54276847e60bdc39fada3aec9cf379.png", size = 1, replace = TRUE))
```

#### RPI
```{r}
url_RPI <- "https://rpiathletics.com/sports/baseball/stats/2022"
tab_RPI <- read_html(url_RPI) %>% html_nodes("table")
RPI_Hitting <- tab_RPI[[1]] %>% html_table(fill = TRUE)
RPI_Pitching <- tab_RPI[[2]] %>% html_table(fill = TRUE)

RPI_Hitting_new <- RPI_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "RPI",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/RPI_Engineers.svg/1200px-RPI_Engineers.svg.png", size = 1, replace = TRUE))

RPI_Pitching_new <- RPI_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "RPI",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/RPI_Engineers.svg/1200px-RPI_Engineers.svg.png", size = 1, replace = TRUE))
```

#### Union
```{r}
url_UC <- "https://unionathletics.com/sports/baseball/stats/2022"
tab_UC <- read_html(url_UC) %>% html_nodes("table")
Union_Hitting <- tab_UC[[1]] %>% html_table(fill = TRUE)
Union_Pitching <- tab_UC[[2]] %>% html_table(fill = TRUE)

Union_Hitting_new <- Union_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Union",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://1000logos.net/wp-content/uploads/2021/07/Union-Dutchmen-logo.png", size = 1, replace = TRUE))

Union_Pitching_new <- Union_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Union",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://1000logos.net/wp-content/uploads/2021/07/Union-Dutchmen-logo.png", size = 1, replace = TRUE))
```

#### Bard
```{r}
url_Bard <- "https://bardathletics.com/sports/baseball/stats/2022"
tab_Bard <- read_html(url_Bard) %>% html_nodes("table")
Bard_Hitting <- tab_Bard[[1]] %>% html_table(fill = TRUE)
Bard_Pitching <- tab_Bard[[2]] %>% html_table(fill = TRUE)

Bard_Hitting_new <- Bard_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Bard",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://bardathletics.com/images/logos/site/site.png", size = 1, replace = TRUE))
  

Bard_Pitching_new <- Bard_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Bard",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://bardathletics.com/images/logos/site/site.png", size = 1, replace = TRUE))
```

#### Vassar
```{r}
url_V <- "https://www.vassarathletics.com/sports/baseball/stats/2022"
tab_V <- read_html(url_V) %>% html_nodes("table")
Vassar_Hitting <- tab_V[[1]] %>% html_table(fill = TRUE)
Vassar_Pitching <- tab_V[[2]] %>% html_table(fill = TRUE)

Vassar_Hitting_new <- Vassar_Hitting %>%
  head(-2) %>%
  select(-23) %>%
  mutate(School = "Vassar",
         wOBA = (0.69*BB + 0.72*HBP + 0.89*(H-`2B`-`3B`-`HR`) + 1.27*`2B` + 1.62*`3B` + 2.10*HR)/(AB + BB + SF + HBP)) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ",") %>%
  select(c(-3)) %>%
  mutate(image = sample("https://www.kindpng.com/picc/m/238-2385745_vassar-college-athletic-logo-hd-png-download.png", size = 1, replace = TRUE))
  

Vassar_Pitching_new <- Vassar_Pitching %>%
  head(-2) %>%
  select(-23) %>%
  separate(col = Player,
         into = c("Player", "First"),
         sep = ","
         ) %>%
  select(c(-3, -26)) %>%
  mutate(School = "Vassar",
         `K/BB` = SO / BB,
         FIP = ((13*HR + 3*BB - 2*SO)/IP),
         image = sample("https://www.kindpng.com/picc/m/238-2385745_vassar-college-athletic-logo-hd-png-download.png", size = 1, replace = TRUE))
```

-------------------------------------------

```{r}

## merging all player data in the liberty league into a single table

LLIndividualPitching_df <- rbind(SLU_Pitching_new, Clarkson_Pitching_new, Rochester_Pitching_new, RIT_Pitching_new, Ithaca_Pitching_new, Skidmore_Pitching_new, RPI_Pitching_new, Union_Pitching_new, Bard_Pitching_new, Vassar_Pitching_new) %>%
  separate(col = `W-L`,
           into = c("W", "L"),
           sep ="-") %>%
  separate(col = `APP-GS`,
           into = c("APP", "GS"),
           sep ="-")

LLIndividualPitching_df$W <- as.numeric(as.character(LLIndividualPitching_df$W))
  
LLIndividualPitching_df$L <- as.numeric(as.character(LLIndividualPitching_df$L))

LLIndividualPitching_df$APP <- as.numeric(as.character(LLIndividualPitching_df$APP))

LLIndividualPitching_df$GS <- as.numeric(as.character(LLIndividualPitching_df$GS))

LLIndividualHitting_df <-
rbind(SLU_Hitting_new, Clarkson_Hitting_new, Rochester_Hitting_new, RIT_Hitting_new, Ithaca_Hitting_new, Skidmore_Hitting_new, RPI_Hitting_new, Union_Hitting_new, Bard_Hitting_new, Vassar_Hitting_new) %>%
  separate(col = `GP-GS`,
           into = c("GP", "GS"),
           sep ="-") %>%
  separate(col = `SB-ATT`,
           into = c("SB", "SBA"),
           sep ="-") %>%
  relocate(wOBA, .before = School)

LLIndividualHitting_df$GP <- as.numeric(as.character(LLIndividualHitting_df$GP))

LLIndividualHitting_df$GS <- as.numeric(as.character(LLIndividualHitting_df$GS))

LLIndividualHitting_df$SB <- as.numeric(as.character(LLIndividualHitting_df$SB))

LLIndividualHitting_df$SBA <- as.numeric(as.character(LLIndividualHitting_df$SBA))

mean(LLIndividualPitching_df$FIP, inf.rm = TRUE)

```

```{r}
ggplot(data = LLIndividualHitting_df %>% filter(School == "SLU"), aes(x = AB, y = OPS)) +
  geom_point()
```

-------------------------------------------
## ShinyApp

```{r}
var_choices_P <- names(LLIndividualPitching_df)[9:25]

var_player_choices_P <-
  LLIndividualPitching_df %>%
  select(Player)

library(shiny)
library(plotly)
library(shinythemes)

ui <- fluidPage(theme = shinytheme("superhero"),
  sidebarLayout(sidebarPanel(
    selectizeInput("Player", label = "player", choices = var_player_choices_P),
    selectizeInput("xchoice", label = "xaxis", choices = var_choices_P),
    selectizeInput("ychoice", label = "yaxis", choices = var_choices_P)),
    mainPanel(plotlyOutput("scattergraph"))
  )
)

server <- function(input, output, session) {
  
  df_sub <- reactive({
    LLIndividualPitching_df
  })
  
  player <- reactive({
    LLIndividualPitching_df %>%
      filter(Player == input$Player)
  })
  
  scatter_plot <- reactive({
    ggplot(df_sub(), aes(x = .data[[input$xchoice]], y = .data[[input$ychoice]], label = Player)) +
      geom_point() +
      geom_smooth() +
      geom_point(data = player(), colour = "red", size = 2) +
      geom_text(data = player(), label = input$Player, vjust=1) +
      theme_grey()
  })
  
  scatter_plotly <- reactive({
    ggplotly(scatter_plot(), tooltip = "label")
  })
  
  output$scattergraph <- renderPlotly({
    scatter_plotly()
  })
  
  
}

shinyApp(ui, server)
```

```{r}
var_choices_H <- names(LLIndividualHitting_df)[3:25]
var_choices_P <- names(LLIndividualPitching_df)[6:22]

library(ggplot2)
library(shiny)
library(ggdark)
library(ggimage)

ui3 <- fluidPage(theme = shinytheme("slate"),
    tabsetPanel(type = "tabs",
    tabPanel("Hitting Leaderboard",
    sidebarLayout(sidebarPanel(
    selectizeInput("StatChoiceH", label = "Pick a Stat", choices = var_choices_H)),
    mainPanel(
    plotOutput("scatterplotHitting")
    )
  )),
    tabPanel("Pitching Leaderboard",
    fluidPage(
    sidebarLayout(sidebarPanel(
    selectizeInput("StatChoiceP", label = "Pick a Stat", choices = var_choices_P)),
    mainPanel(
      plotOutput("scatterplotPitching")
  )))
  ),
    tabPanel("Pitching Scatterplot",
    fluidPage(
    sidebarLayout(sidebarPanel(
    selectizeInput("Player", label = "player", choices = var_player_choices_P),
    selectizeInput("xchoice", label = "xaxis", choices = var_choices_P),
    selectizeInput("ychoice", label = "yaxis", choices = var_choices_P)),
    mainPanel(
      plotlyOutput("scattergraph")
      )))
    ),
  
)
)


server3 <- function(input, output, session) {
  
  Hitting <- reactive({
    LLIndividualHitting_df %>%
    filter(AB >= 10) %>%
    arrange(desc(.data[[input$StatChoiceH]])) %>%
    slice(1:10)
  })
  
   Pitching <- reactive({
    LLIndividualPitching_df %>%
    filter(IP >= 5) %>%
    arrange(desc(.data[[input$StatChoiceP]])) %>%
    slice(1:10)
  })
  
  
  scatterplotH <- reactive({
    ggplot(data = Hitting(),
aes(x = reorder(Player, .data[[input$StatChoiceH]]),y=.data[[input$StatChoiceH]])) +
  geom_image(aes(image=image), size=0.1, by="height") +
  geom_segment(aes(x = Player, xend = Player, y = 0, yend = .data[[input$StatChoiceH]],  color = School)) +
  coord_flip() +
      xlab("Player") + scale_color_manual(values=c("Ithaca" = "Blue","SLU" = "burlywood4",                       "Clarkson" = "darkgreen",
              "Rochester" = "dodgerblue1",
              "RIT" = "chocolate1",
              "Skidmore" = "forestgreen",
              "Union" = "maroon",
              "RPI" = "red2",
              "Bard" = "#FFFFFF",
              "Vassar" = "indianred4")) +
      dark_theme_classic()
  })
  
  scatterplotP <- reactive({
    ggplot(data = Pitching(),
aes(x = reorder(Player, .data[[input$StatChoiceP]]),y=.data[[input$StatChoiceP]])) +
  geom_image(aes(image=image), size=0.1, by="height") +
  geom_segment(aes(x = Player, xend = Player, y = 0, yend = .data[[input$StatChoiceP]], color = School)) +
  coord_flip() +
      xlab("Player") + scale_color_manual(values=c("Ithaca" = "Blue","SLU" = "burlywood4",                       "Clarkson" = "darkgreen",
              "Rochester" = "dodgerblue1",
              "RIT" = "chocolate1",
              "Skidmore" = "forestgreen",
              "Union" = "maroon",
              "RPI" = "red2",
              "Bard" = "#FFFFFF",
              "Vassar" = "indianred4")) +
      dark_theme_classic()
  })
  
  output$scatterplotHitting <- renderPlot({
    scatterplotH()
  })
  
  output$scatterplotPitching <- renderPlot({
    scatterplotP()
  })
  
  df_sub <- reactive({
    LLIndividualPitching_df
  })
  
  player <- reactive({
    LLIndividualPitching_df %>%
      filter(Player == input$Player)
  })
  
  scatter_plot <- reactive({
    ggplot(df_sub(), aes(x = .data[[input$xchoice]], y = .data[[input$ychoice]], label = Player)) +
      geom_point() +
      geom_jitter(alpha = 0.07) +
      geom_smooth() +
      geom_point(data = player(), colour = "red", size = 2) +
      geom_text(data = player(), label = input$Player, vjust=1) +
      theme_grey()
  })
  
  scatter_plotly <- reactive({
    ggplotly(scatter_plot(), tooltip = "label")
  })
  
  output$scattergraph <- renderPlot({
    scatter_plotly()
  })
  
  
}

shinyApp(ui3, server3)
```


